  0%|          | 0/100 [00:00<?, ?it/s]  0%|          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/fs01/home/opent03/detectron/run_div.py", line 78, in <module>
    main()
  File "/fs01/home/opent03/detectron/run_div.py", line 60, in main
    flag, _, _ = permutation_test(distance, 
  File "/fs01/home/opent03/detectron/baselines/divergence.py", line 81, in permutation_test
    est = distance.get_distance(X, Y)
  File "/fs01/home/opent03/detectron/baselines/divergence.py", line 65, in get_distance
    return self.get_h_distance(X, Y)
  File "/fs01/home/opent03/detectron/baselines/divergence.py", line 28, in get_h_distance
    logprob_1 = self._get_kde_estimates(self.bandwidth, X)
  File "/fs01/home/opent03/detectron/baselines/divergence.py", line 20, in _get_kde_estimates
    kernel = stats.gaussian_kde(data, bandwidth)
  File "/h/opent03/.conda/envs/dis/lib/python3.9/site-packages/scipy/stats/_kde.py", line 220, in __init__
    raise ValueError(msg)
ValueError: Number of dimensions is greater than number of samples. This results in a singular data covariance matrix, which cannot be treated using the algorithms implemented in `gaussian_kde`. Note that `gaussian_kde` interprets each *column* of `dataset` to be a point; consider transposing the input to `dataset`.
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [00:16<27:29, 16.66s/it]  2%|▏         | 2/100 [00:33<27:07, 16.61s/it]  3%|▎         | 3/100 [00:49<26:50, 16.61s/it]  4%|▍         | 4/100 [01:06<26:33, 16.60s/it]  5%|▌         | 5/100 [01:23<26:16, 16.59s/it]  6%|▌         | 6/100 [01:39<26:04, 16.65s/it]slurmstepd: error: *** JOB 13679560 ON gpu100 CANCELLED AT 2024-09-30T22:49:09 ***
